# Generated by Django 5.1.3 on 2024-12-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0002_cart_dog_order_delete_dog_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morgan.dog'),
        ),
    ]
