# Generated by Django 5.1.3 on 2024-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0003_cart_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=4),
        ),
    ]
